// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLocalPages.Domain;

#nullable disable

namespace MyLocalPages.Domain.Migrations
{
    [DbContext(typeof(MyLocalPagesContext))]
    [Migration("20221204061003_MyLocalPagesIntialMigrations")]
    partial class MyLocalPagesIntialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("MyLocalPages.Domain.Entities.BusinessDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BusinessDirectories");
                });

            modelBuilder.Entity("MyLocalPages.Domain.Entities.DirectoryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BusinessDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDirectoryId");

                    b.ToTable("DirectoryCategories");
                });

            modelBuilder.Entity("MyLocalPages.Domain.Entities.DirectoryCategory", b =>
                {
                    b.HasOne("MyLocalPages.Domain.Entities.BusinessDirectory", "BusinessDirectory")
                        .WithMany("Categories")
                        .HasForeignKey("BusinessDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessDirectory");
                });

            modelBuilder.Entity("MyLocalPages.Domain.Entities.BusinessDirectory", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
