// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLocalPages.Domain;

#nullable disable

namespace MyLocalPages.Domain.Migrations
{
    [DbContext(typeof(MyLocalPagesContext))]
    [Migration("20221211081558_AddedAuditableEntityFields")]
    partial class AddedAuditableEntityFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("MyLocalPages.Domain.BusinessDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BusinessDirectories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8c5947e-0e57-4d59-9f9a-3da64933ac27"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accommodation, Travel & Tours",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f0e1f767-f97b-434c-a59d-6b0b2f5c0563"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Animals & Pets",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6ef5c444-6098-4934-bb3a-360cdab46e15"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Arts, Crafts & Collectables",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MyLocalPages.Domain.DirectoryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BusinessDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessDirectoryId");

                    b.ToTable("DirectoryCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46b525d9-4e6e-4b27-969c-df6b4d58d50d"),
                            BusinessDirectoryId = new Guid("d8c5947e-0e57-4d59-9f9a-3da64933ac27"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accommodation Booking & Inquiry Services",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c3b8009b-5033-48ab-8a89-ecd3010b42d9"),
                            BusinessDirectoryId = new Guid("d8c5947e-0e57-4d59-9f9a-3da64933ac27"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adventure Tours & Holidays Packages",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cea58b0e-98fd-4836-ad21-82a0f8405196"),
                            BusinessDirectoryId = new Guid("f0e1f767-f97b-434c-a59d-6b0b2f5c0563"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Animal Welfare",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5514e49b-43c9-4f23-887a-11ce99757fa0"),
                            BusinessDirectoryId = new Guid("f0e1f767-f97b-434c-a59d-6b0b2f5c0563"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aquaponics",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ad211ec4-7867-41b5-a1c6-a262679be6a4"),
                            BusinessDirectoryId = new Guid("6ef5c444-6098-4934-bb3a-360cdab46e15"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aboriginal Art & Crafts",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a82053ec-ca1e-4220-ade5-f171658855da"),
                            BusinessDirectoryId = new Guid("6ef5c444-6098-4934-bb3a-360cdab46e15"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Antiques Auctions & Dealers",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MyLocalPages.Domain.DirectoryCategory", b =>
                {
                    b.HasOne("MyLocalPages.Domain.BusinessDirectory", "BusinessDirectory")
                        .WithMany("Categories")
                        .HasForeignKey("BusinessDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessDirectory");
                });

            modelBuilder.Entity("MyLocalPages.Domain.BusinessDirectory", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
